# config/loss_function/CrossEntropy/R34.yaml

# Paths Configuration
paths:
  run_name: "loss_function/CrossEntropy/R34"
  output_path_model: model
  output_path_dict: training_dict
  hdf5_path: data/images_224.hdf5

# Model Configuration
model:
  name: Resnet34  # Options: Resnet18, Resnet34, Resnet50, Resnet101, Resnet152, Densenet121, Densenet169, Densenet201, Vision
  num_classes: 2
  input_size: 224
  use_checkpointing: False
  dropout_p: 0.5

# Optimizer Configuration
optimizer:
  type: Adam  # Options: Adam, AdamW
  learning_rate: 0.001

# Scheduler Configuration
scheduler:
  type: cosine_warm_up  # Options: reduce_on_plateau, cosine_warm_up
  factor: 0.1
  patience: 3
  warmup_ratio: 0.1
  
# HDF5Dataset function configuration
HDF5Dataset:
  cache_in_memory: True

# Data Augmentation Configuration
augmentation:
  type: none  # Options: none, basic, advanced, mixup, cutmix
  mixup_alpha: 1.0
  cutmix_alpha: 1.0

# Training Parameters
training:
  batch_size: 32
  epochs: 50
  folds: 5
  test_size: 0.15
  #val_size: 0.15
  tune_hyperparameters: False
  n_trials: 20
  mc_iterations: 50  # Number of Monte Carlo iterations
  seed: 42
  use_mixed_precision: True
  early_stopping_patience: 7
  early_stopping_delta: 0.001
  gradient_clipping: 1.0
  
  
# Profiler Configuration
profiler:
  activation: False
  wait_steps: 1
  warmup_steps: 1
  active_steps: 3
  repeat: 2

# Tensorboard Configuration
tensorboard:
  activation: False

# Miscellaneous Settings
misc:
  cuda: 2
  criterion_weight: None
  
data:
  num_workers: 10
  prefetch_factor : 10
  

# Loss Function
loss_function: CrossEntropyLoss  # Options: CrossEntropyLoss, FocalLoss
