paths:
  run_name: bias2/stain/model_efficientnet_b2
  output_path_model: model
  output_path_dict: training_dict
  hdf5_path: data/images_224.hdf5
model:
  name: efficientnet_b2
  multihead: false
  label: stain
  num_classes: 4
  input_size: 224
  use_checkpointing: false
  dropout_p: 0.5
multihead:
  labels:
  - class
  - stain
  - scanner
  num_classes:
  - 2
  - 4
  - 3
  loss_functions:
  - CrossEntropyLoss
  - FocalLoss
  - CrossEntropyLoss
  loss_weights:
  - 1.0
  - 0.5
  - 2.0
optimizer:
  type: Adam
  learning_rate: 0.0001
scheduler:
  type: reduce_on_plateau
  factor: 0.1
  patience: 3
  warmup_ratio: 0.1
HDF5Dataset:
  cache_in_memory: true
augmentation:
  type: basic
  mixup_alpha: 1.0
  cutmix_alpha: 1.0
training:
  split_level: wsi
  batch_size: 32
  accumulation_steps: 1
  epochs: 50
  folds: 5
  test_size: 0.15
  tune_hyperparameters: false
  n_trials: 20
  mc_iterations: 50
  seed: 42
  use_mixed_precision: true
  early_stopping_patience: 7
  early_stopping_delta: 0.0001
  gradient_clipping: 1.0
profiler:
  activation: false
  wait_steps: 1
  warmup_steps: 1
  active_steps: 3
  repeat: 2
tensorboard:
  activation: false
misc:
  cuda: 0
  criterion_weight: None
data:
  num_workers: 4
  prefetch_factor: 4
loss_function: CrossEntropyLoss
