paths:
  run_name: image_size_1024/augmentation_cutmix/scheduler_type_cosine_warm_up/criterion_weight_None/optimizer_type_AdamW/optimizer_lr_0.0001/loss_function_CrossEntropyLoss/model_Densenet121
  output_path_model: model
  output_path_dict: training_dict
  hdf5_path: data/images_1024.hdf5
model:
  name: Densenet121
  num_classes: 2
  input_size: 1024
  use_checkpointing: false
  dropout_p: 0.5
optimizer:
  type: AdamW
  learning_rate: 0.0001
scheduler:
  type: cosine_warm_up
  factor: 0.1
  patience: 3
  warmup_ratio: 0.1
HDF5Dataset:
  cache_in_memory: true
augmentation:
  type: cutmix
  mixup_alpha: 1.0
  cutmix_alpha: 1.0
training:
  batch_size: 32
  epochs: 50
  folds: 5
  test_size: 0.15
  tune_hyperparameters: false
  n_trials: 20
  mc_iterations: 50
  seed: 42
  use_mixed_precision: true
  early_stopping_patience: 7
  early_stopping_delta: 0.001
  gradient_clipping: 1.0
profiler:
  activation: false
  wait_steps: 1
  warmup_steps: 1
  active_steps: 3
  repeat: 2
tensorboard:
  activation: false
misc:
  cuda: 6
  criterion_weight: None
data:
  num_workers: 4
  prefetch_factor: 4
loss_function: CrossEntropyLoss
