paths:
  run_name: multihead_scanner/TotalCrossEntropy/Resnet50/scale_0
  output_path_model: model
  output_path_dict: training_dict
  hdf5_path: data/images_224.hdf5
model:
  name: Resnet50
  multihead: true
  label: class
  num_classes: 2
  input_size: 224
  use_checkpointing: false
  dropout_p: 0.5
multihead:
  labels:
  - class
  - scanner
  num_classes:
  - 2
  - 3
  loss_functions:
  - TotalCrossEntropyLoss
  - TotalCrossEntropyLoss
  loss_weights:
  - 1.0
  - 1.0
optimizer:
  type: Adam
  learning_rate: 0.0001
scheduler:
  type: reduce_on_plateau
  factor: 0.1
  patience: 3
  warmup_ratio: 0.1
HDF5Dataset:
  cache_in_memory: true
augmentation:
  type: none
  mixup_alpha: 1.0
  cutmix_alpha: 1.0
training:
  batch_size: 32
  epochs: 50
  folds: 5
  test_size: 0.15
  tune_hyperparameters: false
  n_trials: 20
  mc_iterations: 50
  seed: 42
  use_mixed_precision: true
  early_stopping_patience: 15
  early_stopping_delta: 0.0005
  gradient_clipping: 1.0
profiler:
  activation: false
  wait_steps: 1
  warmup_steps: 1
  active_steps: 3
  repeat: 2
tensorboard:
  activation: false
misc:
  cuda: 3
  criterion_weight: None
data:
  num_workers: 4
  prefetch_factor: 4
loss_function: CrossEntropyLoss
